
var TaskEndReasons = [
  "SUCCESS",
  "RESUBMITTED",
  "TASK_RESULT_LOST",
  "TASK_KILLED",
  "FETCH_FAILED",
  "EXCEPTION_FAILURE",
  "TASK_COMMIT_DENIED",
  "EXECUTOR_LOST_FAILURE",
  "UNKNOWN_REASON"
];

var LocalityLevels = [
  "PROCESS_LOCAL", "NODE_LOCAL", "NO_PREF", "RACK_LOCAL", "ANY"
];

