#!/usr/bin/env bash

host=localhost
port=27017
db=spree

while getopts ":h:p:d:" opt; do
  case $opt in
    h)
      host="$OPTARG"
      ;;
    p)
      port="$OPTARG"
      ;;
    d)
      db="$OPTARG"
      ;;
    \?)
      break
      ;;
  esac
done
shift $((OPTIND-1))

export MONGO_URL="mongodb://$host:$port/$db"
export MONGO_OPLOG_URL="mongodb://$host:$port/local"

echo "Starting Meteor pointing at mongo URL $MONGO_URL (oplog url: $MONGO_OPLOG_URL)"

meteor "$@"
